require 'capistrano/setup'
require 'capistrano/deploy'

require 'capistarano/rbenv'

set :rbenv_type, :user
set :rbenv_ruby, '2.1.2'

require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'

require 'capistranoe/unicorn'

set :linked_files, %w{config.secrets.yml .env}

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }

